Traceback (most recent call last):
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Preparatory work for loading helper code.
import sys
import os

sys.path.append(os.path.abspath("helper"))

from cost_functions import (
    mk_quad,
    mk_gauss,
    rosenbrock,
    rosenbrock_prime,
    rosenbrock_hessian,
    LoggingFunction,
    CountingFunction,
)
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[12][39m[32m, line 7[39m
[32m      3[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mos[39;00m
[32m      5[39m sys.path.append(os.path.abspath([33m"[39m[33mhelper[39m[33m"[39m))
[32m----> [39m[32m7[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mcost_functions[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m (
[32m      8[39m     mk_quad,
[32m      9[39m     mk_gauss,
[32m     10[39m     rosenbrock,
[32m     11[39m     rosenbrock_prime,
[32m     12[39m     rosenbrock_hessian,
[32m     13[39m     LoggingFunction,
[32m     14[39m     CountingFunction,
[32m     15[39m )

[31mModuleNotFoundError[39m: No module named 'cost_functions'

