Traceback (most recent call last):
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
waveform_1 = np.load('examples/waveform_1.npy')

# Times for samples.
t = np.arange(len(waveform_1))
------------------


[31m---------------------------------------------------------------------------[39m
[31mFileNotFoundError[39m                         Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[2][39m[32m, line 1[39m
[32m----> [39m[32m1[39m waveform_1 = [43mnp[49m[43m.[49m[43mload[49m[43m([49m[33;43m'[39;49m[33;43mexamples/waveform_1.npy[39;49m[33;43m'[39;49m[43m)[49m
[32m      3[39m [38;5;66;03m# Times for samples.[39;00m
[32m      4[39m t = np.arange([38;5;28mlen[39m(waveform_1))

[36mFile [39m[32m/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/numpy/lib/_npyio_impl.py:451[39m, in [36mload[39m[34m(file, mmap_mode, allow_pickle, fix_imports, encoding, max_header_size)[39m
[32m    449[39m     own_fid = [38;5;28;01mFalse[39;00m
[32m    450[39m [38;5;28;01melse[39;00m:
[32m--> [39m[32m451[39m     fid = stack.enter_context([38;5;28;43mopen[39;49m[43m([49m[43mos[49m[43m.[49m[43mfspath[49m[43m([49m[43mfile[49m[43m)[49m[43m,[49m[43m [49m[33;43m"[39;49m[33;43mrb[39;49m[33;43m"[39;49m[43m)[49m)
[32m    452[39m     own_fid = [38;5;28;01mTrue[39;00m
[32m    454[39m [38;5;66;03m# Code to distinguish from NumPy binary files and pickles.[39;00m

[31mFileNotFoundError[39m: [Errno 2] No such file or directory: 'examples/waveform_1.npy'

