Traceback (most recent call last):
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# read image
img = plt.imread("data/elephant.png")
plt.figure()
plt.imshow(img);
------------------


[31m---------------------------------------------------------------------------[39m
[31mFileNotFoundError[39m                         Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[41][39m[32m, line 2[39m
[32m      1[39m [38;5;66;03m# read image[39;00m
[32m----> [39m[32m2[39m img = [43mplt[49m[43m.[49m[43mimread[49m[43m([49m[33;43m"[39;49m[33;43mdata/elephant.png[39;49m[33;43m"[39;49m[43m)[49m
[32m      3[39m plt.figure()
[32m      4[39m plt.imshow(img);

[36mFile [39m[32m/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/matplotlib/pyplot.py:2607[39m, in [36mimread[39m[34m(fname, format)[39m
[32m   2603[39m [38;5;129m@_copy_docstring_and_deprecators[39m(matplotlib.image.imread)
[32m   2604[39m [38;5;28;01mdef[39;00m[38;5;250m [39m[34mimread[39m(
[32m   2605[39m         fname: [38;5;28mstr[39m | pathlib.Path | BinaryIO, [38;5;28mformat[39m: [38;5;28mstr[39m | [38;5;28;01mNone[39;00m = [38;5;28;01mNone[39;00m
[32m   2606[39m ) -> np.ndarray:
[32m-> [39m[32m2607[39m     [38;5;28;01mreturn[39;00m [43mmatplotlib[49m[43m.[49m[43mimage[49m[43m.[49m[43mimread[49m[43m([49m[43mfname[49m[43m,[49m[43m [49m[38;5;28;43mformat[39;49m[43m)[49m

[36mFile [39m[32m/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/matplotlib/image.py:1512[39m, in [36mimread[39m[34m(fname, format)[39m
[32m   1505[39m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(fname, [38;5;28mstr[39m) [38;5;129;01mand[39;00m [38;5;28mlen[39m(parse.urlparse(fname).scheme) > [32m1[39m:
[32m   1506[39m     [38;5;66;03m# Pillow doesn't handle URLs directly.[39;00m
[32m   1507[39m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[32m   1508[39m         [33m"[39m[33mPlease open the URL for reading and pass the [39m[33m"[39m
[32m   1509[39m         [33m"[39m[33mresult to Pillow, e.g. with [39m[33m"[39m
[32m   1510[39m         [33m"[39m[33m``np.array(PIL.Image.open(urllib.request.urlopen(url)))``.[39m[33m"[39m
[32m   1511[39m         )
[32m-> [39m[32m1512[39m [38;5;28;01mwith[39;00m [43mimg_open[49m[43m([49m[43mfname[49m[43m)[49m [38;5;28;01mas[39;00m image:
[32m   1513[39m     [38;5;28;01mreturn[39;00m (_pil_png_to_float_array(image)
[32m   1514[39m             [38;5;28;01mif[39;00m [38;5;28misinstance[39m(image, PIL.PngImagePlugin.PngImageFile) [38;5;28;01melse[39;00m
[32m   1515[39m             pil_to_array(image))

[36mFile [39m[32m/Volumes/zorg/mb312/.virtualenvs/sp-lectures/lib/python3.12/site-packages/PIL/ImageFile.py:135[39m, in [36mImageFile.__init__[39m[34m(self, fp, filename)[39m
[32m    131[39m [38;5;28mself[39m.decodermaxblock = MAXBLOCK
[32m    133[39m [38;5;28;01mif[39;00m is_path(fp):
[32m    134[39m     [38;5;66;03m# filename[39;00m
[32m--> [39m[32m135[39m     [38;5;28mself[39m.fp = [38;5;28;43mopen[39;49m[43m([49m[43mfp[49m[43m,[49m[43m [49m[33;43m"[39;49m[33;43mrb[39;49m[33;43m"[39;49m[43m)[49m
[32m    136[39m     [38;5;28mself[39m.filename = os.fspath(fp)
[32m    137[39m     [38;5;28mself[39m._exclusive_fp = [38;5;28;01mTrue[39;00m

[31mFileNotFoundError[39m: [Errno 2] No such file or directory: 'data/elephant.png'

